name: Grade

on: push

jobs:
  grade:
    runs-on: ubuntu-latest
    container: gokceuludogan/cmpe230_spring24:latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run
        run:
          make grade -s > grade.txt
          
      - name: Grade
        run: |
          cat grade.txt
          echo "Grade: " >> $GITHUB_STEP_SUMMARY 
          cat grade.txt >> $GITHUB_STEP_SUMMARY
          echo "output=$(cat grade.txt)" >> $GITHUB_ENV
